version: '3.7'

services:
  db:
    image: postgres:12.2
    container_name: g-crawler_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
